offer/urls.py
# -*- coding: utf-8 -*-
# __author__ = '40huo'
from django.conf.urls import url

from offer import views

app_name = 'offer'
urlpatterns = [
    url(r'^$', view=views.index, name='index'),
    url(r'^add/$', view=views.add_offer, name='add_offer'),
    url(r'^edit/(?P<offer_id>\d+)/$', view=views.update_offer, name='edit_offer'),
    url(r'^delete/(?P<offer_id>\d+)/$', view=views.delete_offer, name='delete_offer'),
]

offerknow/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('offer.urls')),
    url(r'^accounts/', include('account.urls', namespace="account")),
]

offer/models.py
from django.db import models


# Create your models here.
class Offer(models.Model):
    """
    offer 类
    """
    RESULT_CHOICES = (
        ('unknown', '待定'),
        ('rejected', '回绝'),
        ('accepted', '收到 offer'),
    )

    company = models.CharField(verbose_name='公司', max_length=64)
    url = models.CharField(verbose_name='网址', max_length=256)
    application_method = models.CharField(verbose_name='申请渠道', max_length=64)
    application_date = models.DateField(verbose_name='申请日期')
    last_interview_date = models.DateField(verbose_name='最后更新时间')
    status = models.CharField(verbose_name='状态', max_length=32)
    result = models.CharField(verbose_name='结果', max_length=64, choices=RESULT_CHOICES)

offer/forms.py
from django import forms

from offer.models import Offer


class OfferForm(forms.ModelForm):
    """
    表单类
    """

    def __init__(self, *args, **kwargs):
        super(OfferForm, self).__init__(*args, **kwargs)

        # 选择框
        self.fields['result'].widget.attrs['class'] = 'ui search dropdown'

        # 日期控件
        self.fields['application_date'].widget.attrs['class'] = 'ui calendar'
        self.fields['last_interview_date'].widget.attrs['class'] = 'ui calendar'

    def clean(self):
        """
        对不以 http 开头的 URL 做处理
        :return:
        """
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http'):
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data

    class Meta:
        model = Offer
        fields = '__all__'


class DeleteOfferForm(forms.ModelForm):
    """
    删除表单
    """

    class Meta:
        model = Offer
        fields = ()

offer/views.py
import logging

from django.shortcuts import render, redirect, get_object_or_404

from offer.forms import OfferForm, DeleteOfferForm
from offer.models import Offer


# Create your views here.


def index(request):
    """
    首页展示
    :param request:
    :return:
    """
    application_list = Offer.objects.order_by('-application_date')
    context = {
        'application_list': application_list,
    }
    return render(request=request, template_name='offer/index.html', context=context)


def add_offer(request):
    """
    添加 offer 信息
    :param request:
    :return:
    """
    form = OfferForm()

    if request.method == 'POST':
        form = OfferForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(to='/')
        else:
            logging.error(form.errors)

    return render(request=request, template_name='offer/add_offer.html', context={'form': form})


def update_offer(request, offer_id):
    """
    编辑 offer 信息
    :param request:
    :param offer_id:
    :return:
    """
    if request.method == 'POST':
        form = OfferForm(request.POST)

        if form.is_valid():
            offer = get_object_or_404(Offer, pk=offer_id)
            form = OfferForm(request.POST, instance=offer)
            form.save(commit=True)
            return redirect('/')
        else:
            offer = get_object_or_404(Offer, pk=offer_id)
            form = OfferForm(instance=offer)
    else:
        offer = get_object_or_404(Offer, pk=offer_id)
        form = OfferForm(instance=offer)

    return render(request=request, template_name='offer/edit_offer.html', context={'form': form})


def delete_offer(request, offer_id):
    """
    删除 offer 信息
    :param request:
    :param offer_id:
    :return:
    """
    offer = get_object_or_404(Offer, pk=offer_id)
    if request.method == 'POST':
        form = DeleteOfferForm(request.POST, instance=offer)

        if form.is_valid():
            offer.delete()
            return redirect('/')
        else:
            logging.error(form.errors)

    return redirect('/')

templates/offer/add_offer.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Add Offer
{% endblock %}

{% block body %}
    <div class="ui main container">
        <h2 class="ui dividing header">添加 offer 信息</h2>
        {% include 'offer/offerform.html' %}
        <script src="{% static 'offer/js/offer.js' %}"></script>
    </div>
{% endblock %}

templates/offer/edit_offer.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Edit Offer
{% endblock %}

{% block body %}
    <div class="ui main container">
        <h2 class="ui dividing header">更新 offer 信息</h2>
        {% include 'offer/offerform.html' %}
        <script src="{% static 'offer/js/offer.js' %}"></script>
    </div>
{% endblock %}

templates/offer/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Your offer collector!
{% endblock %}

{% block body %}
    <div class="ui main container">
        <h2 class="ui dividing header">offer 信息</h2>
        {% if application_list %}
            <table class="ui celled single line striped table">
                <thead>
                <tr>
                    <th>公司</th>
                    <th>网址</th>
                    <th>申请日期</th>
                    <th>申请渠道</th>
                    <th>最后更新时间</th>
                    <th>状态</th>
                    <th>结果</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for application in application_list %}
                    <tr>
                        <td>{{ application.company }}</td>
                        <td><a href="{{ application.url }}" target="_blank">{{ application.url }}</a></td>
                        <td>{{ application.application_date }}</td>
                        <td>{{ application.application_method }}</td>
                        <td>{{ application.last_interview_date }}</td>
                        <td>{{ application.status }}</td>
                        <td>{{ application.get_result_display }}</td>
                        <td>
                            <button class="ui primary small button"
                                    onclick="location.href='{% url 'offer:edit_offer' application.id %}';">
                                修改
                            </button>
                            <form id="form-delete-offer" method="post" style="display: inline;"
                                  action="{% url 'offer:delete_offer' application.id %}">
                                {% csrf_token %}
                                <button class="ui red small button" id="delete-btn">删除</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
    <script src="{% static 'offer/js/offer.js' %}"></script>
{% endblock %}

templates/offer/offerform.html
<form class="ui form" id="form-offer" method="post" action="{% url 'offer:add_offer' %}">
    <div class="ui middle aligned centered grid">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="row">
                <div class="two wide right aligned column">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                {% if field.name == 'application_date' %}
                    <div class="six wide column" id="rangestart">
                        <div class="ui left icon fluid input">
                            <i class="calendar icon"></i>
                            {{ field }}
                        </div>
                    </div>
                {% elif field.name == 'last_interview_date' %}
                    <div class="six wide column" id="rangeend">
                        <div class="ui left icon fluid input">
                            <i class="calendar icon"></i>
                            {{ field }}
                        </div>
                    </div>
                {% else %}
                    <div class="six wide column ">
                        <div class="ui left icon fluid input">
                            {% if field.name == 'company' %}
                                <i class="home icon"></i>
                            {% elif field.name == 'url' %}
                                <i class="external icon"></i>
                            {% elif field.name == 'status' %}
                                <i class="unordered list icon"></i>
                            {% elif field.name == 'application_method' %}
                                <i class="ticket icon"></i>
                            {% elif field.name == 'result' %}
                                <i class="checkmark icon"></i>
                            {% endif %}
                            {{ field }}
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        <div class="row">
            {#                    offset #}
            <div class="two wide column"></div>
            <div class="four wide column">
                <button type="submit" class="ui positive fluid button" id="submit">提交</button>
            </div>
        </div>
    </div>
</form>