account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (login, logout, password_change,
                                       password_change_done, password_reset,
                                       password_reset_complete,
                                       password_reset_confirm,
                                       password_reset_done)

from .views import (activate, activation_complete, register,
                    registration_closed, registration_complete)

urlpatterns = [
    url(r'^register/$', register, name='users_register'),
    url(r'^register/closed/$', registration_closed, name='users_registration_closed'),
    url(r'^register/complete/$', registration_complete, name='users_registration_complete'),
    url(r'^activate/complete/$', activation_complete, name='users_activation_complete'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='users_activate'),

    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='users_login'),
    url(r'^logout/$', logout, {'template_name': 'users/logout.html'}, name='users_logout'),
    url(r'^password_change/$', password_change,
        {
            'template_name': 'users/password_change_form.html',
            'post_change_redirect': 'users_password_change_done'
        },
        name='users_password_change'),
    url(r'^password_change/done/$', password_change_done,
        {'template_name': 'users/password_change_done.html'},
        name='users_password_change_done'),
    url(r'^password_reset/$', password_reset,
        {
            'template_name': 'users/password_reset_form.html',
            'email_template_name': 'users/password_reset_email.html',
            'subject_template_name': 'users/password_reset_subject.html',
            'post_reset_redirect': 'users_password_reset_done'
        },
        name='users_password_reset'),
    url(r'^password_reset/done/$', password_reset_done,
        {'template_name': 'users/password_reset_done.html'},
        name='users_password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,
        {
            'template_name': 'users/password_reset_confirm.html',
            'post_reset_redirect': 'users_password_reset_complete'
        },
        name='users_password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete,
        {'template_name': 'users/password_reset_complete.html'},
        name='users_password_reset_complete'),
]

offer/urls.py
# -*- coding: utf-8 -*-
# __author__ = '40huo'
from django.conf.urls import url

from offer import views

app_name = 'offer'
urlpatterns = [
    url(r'^$', view=views.index, name='index'),
    url(r'^add/$', view=views.add_offer, name='add_offer'),
    url(r'^edit/(?P<offer_id>\d+)/$', view=views.update_offer, name='edit_offer'),
    url(r'^delete/(?P<offer_id>\d+)/$', view=views.delete_offer, name='delete_offer'),
]

offerknow/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('offer.urls')),
    url(r'^accounts/', include('account.urls', namespace="account")),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html" charset="UTF-8">
    <meta name="description" content="Offer management system based on Django">
    <meta name="author" content="40huo">
    <title>OfferKnow - {% block title %}Your offer collector!{% endblock %}
    </title>

    <!--css-->
    <link href="https://cdn.bootcss.com/semantic-ui/2.2.13/semantic.css" rel="stylesheet">
    <link href="{% static 'offer/css/offer.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/semantic-ui-calendar/0.0.8/calendar.css" rel="stylesheet">
    <!--JS-->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/semantic-ui/2.2.13/semantic.js"></script>
    <script src="https://cdn.bootcss.com/semantic-ui-calendar/0.0.8/calendar.js"></script>
</head>
<body>
<div class="ui huge fixed borderless menu" id="nav-menu">
    <a class="header huge item" href="/"><h1>OfferKnow</h1></a>
    <a class="item" href="/">Home</a>
    <a class="item" href="{% url 'offer:add_offer' %}">Add</a>
    <div class="right menu item">
        {% if request.user.is_authenticated %}
            <a class="ui primary button" href="{% url 'account:users_login' %}">{{request.user.user_name}}</a>
        {% endif %}
        {% if not request.user.is_authenticated%}
            <a class="ui primary button" href="{% url 'account:users_login' %}">Sign In</a>
        {% endif %}
    </div>
</div>
{% block body %}{% endblock %}
</body>
</html>