account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (login, logout, password_change,
                                       password_change_done, password_reset,
                                       password_reset_complete,
                                       password_reset_confirm,
                                       password_reset_done)

from .views import (activate, activation_complete, register,
                    registration_closed, registration_complete)

urlpatterns = [
    url(r'^register/$', register, name='users_register'),
    url(r'^register/closed/$', registration_closed, name='users_registration_closed'),
    url(r'^register/complete/$', registration_complete, name='users_registration_complete'),
    url(r'^activate/complete/$', activation_complete, name='users_activation_complete'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='users_activate'),

    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='users_login'),
    url(r'^logout/$', logout, {'template_name': 'users/logout.html'}, name='users_logout'),
    url(r'^password_change/$', password_change,
        {
            'template_name': 'users/password_change_form.html',
            'post_change_redirect': 'users_password_change_done'
        },
        name='users_password_change'),
    url(r'^password_change/done/$', password_change_done,
        {'template_name': 'users/password_change_done.html'},
        name='users_password_change_done'),
    url(r'^password_reset/$', password_reset,
        {
            'template_name': 'users/password_reset_form.html',
            'email_template_name': 'users/password_reset_email.html',
            'subject_template_name': 'users/password_reset_subject.html',
            'post_reset_redirect': 'users_password_reset_done'
        },
        name='users_password_reset'),
    url(r'^password_reset/done/$', password_reset_done,
        {'template_name': 'users/password_reset_done.html'},
        name='users_password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,
        {
            'template_name': 'users/password_reset_confirm.html',
            'post_reset_redirect': 'users_password_reset_complete'
        },
        name='users_password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete,
        {'template_name': 'users/password_reset_complete.html'},
        name='users_password_reset_complete'),
]

offer/urls.py
# -*- coding: utf-8 -*-
# __author__ = '40huo'
from django.conf.urls import url

from offer import views

app_name = 'offer'
urlpatterns = [
    url(r'^$', view=views.index, name='index'),
    url(r'^add/$', view=views.add_offer, name='add_offer'),
    url(r'^edit/(?P<offer_id>\d+)/$', view=views.update_offer, name='edit_offer'),
    url(r'^delete/(?P<offer_id>\d+)/$', view=views.delete_offer, name='delete_offer'),
]

offerknow/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('offer.urls')),
    url(r'^accounts/', include('account.urls', namespace="account")),
]

templates/users/activate.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<p>{% trans "Account activation failed" %}</p>
{% endblock %}

templates/users/activation_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<p>{% trans "Your account is now activated." %}</p>
{% endblock %}

templates/users/activation_email.html
{% load i18n %}

{% trans "Thank you for registering an account at" %} {{ site.name }}
{% trans "To activate your registration, please visit the following page:" %}

{{ protocol }}://{{ site.domain }}{% url 'users_activate' uid token %}

{% blocktrans %}This link will expire in {{ expiration_days }} days.{% endblocktrans %}

{% trans "If you didn't register this account you can simply delete this email and we won't bother you again." %}

templates/users/activation_email_subject.html
{% load i18n %}{% trans "Account activation on" %} {{ site.name }}

templates/users/login.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<div class="ui main container">
    <h2 class="ui dividing header">登陆</h2>
    <form class="ui form" id="form-login" method="post" action="">
    <div class="ui middle aligned centered grid">
		{% if form.errors %}
			{% include "users/partials/errors.html" %}
		{% endif %}
		{% csrf_token %}
		{% for field in form %}
			{% include "users/partials/field.html" %}
		{% endfor %}
        <div class="row">
            <div class="two wide column">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            </div>
            <div class="four wide column">
                <button type="submit" class="ui positive fluid button" id="submit" value="{% trans 'Log in' %}" >登陆</button>
            </div>
        </div>

		<input type="hidden" name="next" value="{{ next }}" />
		<p><a href="{% url 'account:users_password_reset' %}">{% trans "Forgot password" %}</a></p>
		<p><a href="{% url 'account:users_register' %}">{% trans "Register" %}</a></p>
    </div>
	</form>
</div>
{% endblock %}

templates/users/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<p>{% trans "Password changed" %}</p>
{% endblock %}

templates/users/password_change_form.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<div class="form-wrapper">
	<form method="post" action="">
		{% if form.errors %}
			{% include "users/partials/errors.html" %}
		{% endif %}
		{% csrf_token %}
		{% for field in form %}
			{% include "users/partials/field.html" %}
		{% endfor %}
		<div class="button-wrapper submit">
			<input type="submit" value="{% trans 'Change Password' %}" />
		</div>
	</form>
</div>
{% endblock %}

templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<p>{% trans "Password reset successfully" %}</p>
<p><a href="{% url 'users_login' %}">{% trans "Log in" %}</a></p>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
{% if validlink %}
	<div class="form-wrapper">
		<form method="post" action="">
			{% if form.errors %}
				{% include "users/partials/errors.html" %}
			{% endif %}
			{% csrf_token %}
			{% for field in form %}
				{% include "users/partials/field.html" %}
			{% endfor %}
			<div class="button-wrapper submit">
				<input type="submit" value="{% trans 'Submit' %}" />
			</div>
		</form>
	</div>
{% else %}
	<p>{% trans "Password reset failed" %}</p>
{% endif %}
{% endblock %}

templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<p>{% trans "Email with password reset instructions has been sent." %}</p>
{% endblock %}

templates/users/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<div class="form-wrapper">
	<form method="post" action="">
		{% if form.errors %}
			{% include "users/partials/errors.html" %}
		{% endif %}
		{% csrf_token %}
		{% for field in form %}
			{% include "users/partials/field.html" %}
		{% endfor %}
		<div class="button-wrapper submit">
			<input type="submit" value="{% trans 'Submit' %}" />
		</div>
	</form>
</div>
{% endblock %}

templates/users/registration_closed.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
    <div class="ui main container">
    <h1>{% trans "Sign Up Closed" %}</h1>
    <p>{% trans "We are sorry, but the sign up is currently closed." %}</p>
    </div>

{% endblock %}

templates/users/registration_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
    <div class="ui main container">
        <p>{% trans "注册完成." %}</p>
    </div>
{% endblock %}

templates/users/registration_form.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<div class="ui main container">
	<form method="post" action="">
		{% if form.errors %}
			{% include "users/partials/errors.html" %}
		{% endif %}
		{% csrf_token %}
		{% for field in form %}
			{% include "users/partials/field.html" %}
		{% endfor %}
        <div class="row">
            <div class="two wide column">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            </div>
            <div class="four wide column">
                <button type="submit" class="ui positive fluid button" id="submit" value="{% trans 'Register' %}" >注册</button>
            </div>
        </div>
	</form>
</div>
{% endblock %}